[build]
command = "npm run netlify-deploy"
environment = { NODE_OPTIONS = "--max_old_space_size=8192" }

[context]
# Add any Netlify context-specific settings here

[functions]
# Add any Netlify functions settings here

[plugins]
# Add any Netlify plugin settings here
