service: be-well-therapy

plugins:
  - serverless-apigw-binary

custom:
  # setting up a custom variable for the env option passed in
  env: ${opt:env}
  apigwBinary:
    #list of mime-types
    types:
      - "*/*"
provider:
  name: aws
  runtime: nodejs14.x
  stage: ${self:custom.env}
  environment:
    # telling npm this is the production version
    NODE_ENV: production
    CURRENT_STAGE: ${self:custom.env}
  # setting the APIG stage to mimic the custom env variable
  region: us-east-1

functions:
  server:
    handler: index.server
    events:
      - http: ANY /
      - http: ANY /{proxy+}

# ACM/Route53 was done manually due to some bugs
# in the plugins